---
# SPDX-License-Identifier: Apache-2.0
# Example: Matrix build for multiple platform×template combinations
# Similar to JJB packer-builder-jobs configuration

name: Packer Matrix Build

on:
  workflow_dispatch:
  schedule:
    - cron: "00 1 1 * *" # Monthly on the 1st
  push:
    branches:
      - master
    paths:
      - "packer/**"

jobs:
  matrix-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Matches JJB packer-builder-jobs configuration
        platform:
          - centos-7
          - centos-cs-8
          - centos-cs-9
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
        template:
          - builder
        # Add more combinations as needed
        include:
          # Docker images (from packer-docker-jobs)
          - platform: ubuntu-22.04
            template: docker
          - platform: ubuntu-20.04
            template: docker
          # Helm images (from packer-helm-jobs)
          - platform: ubuntu-18.04
            template: helm
          - platform: centos-7
            template: helm
          # Robot images (from packer-robot-jobs)
          - platform: ubuntu-22.04
            template: robot
          - platform: ubuntu-24.04
            template: robot
          # Mininet images (from packer-mininet-ovs-217-jobs)
          - platform: ubuntu-22.04
            template: mininet-ovs-217
          - platform: ubuntu-24.04
            template: mininet-ovs-217

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true

      - name: Update submodules
        run: git submodule update --init

      - name: Build ${{ matrix.platform }} - ${{ matrix.template }}
        uses: lfit/packer-openstack-bastion-action@v1
        with:
          mode: build
          packer_template: "templates/${{ matrix.template }}.pkr.hcl"
          packer_vars_file: "common-packer/vars/${{ matrix.platform }}.pkrvars.hcl"
          packer_working_dir: "packer"

          # Cloud configuration
          cloud_env_json: ${{ secrets.CLOUD_ENV_JSON_B64 }}

          # OpenStack credentials
          openstack_auth_url: ${{ secrets.OPENSTACK_AUTH_URL }}
          openstack_project_id: ${{ secrets.OPENSTACK_PROJECT_ID }}
          openstack_username: ${{ secrets.OPENSTACK_USERNAME }}
          openstack_password: ${{ secrets.OPENSTACK_PASSWORD_B64 }}
          openstack_network_id: ${{ secrets.OPENSTACK_NETWORK_ID }}

          # Tailscale
          tailscale_auth_key: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Report build status
        if: always()
        run: |
          echo "### Build Result: ${{ matrix.platform }} - ${{ matrix.template }}" >> $GITHUB_STEP_SUMMARY
          echo "Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
