---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: "Packer Build with VexxHost Tailscale Bastion"
description: "Build OpenStack images using Packer through a Tailscale bastion host"
author: "The Linux Foundation"

inputs:
  # Operation Mode
  mode:
    description: "Operation mode: 'validate' (syntax check only) or 'build' (full build with bastion)"
    required: false
    default: "build"

  # Packer Configuration
  packer_template:
    description: "Path to Packer template file (relative to packer_working_dir) - ignored in validate mode which validates all templates"
    required: false
    default: ""
  packer_vars_file:
    description: "Path to Packer variables file (relative to packer_working_dir) - ignored in validate mode which validates all varfiles"
    required: false
    default: ""
  packer_working_dir:
    description: "Working directory containing Packer files (will search for packer/ or common-packer/ subdirectory)"
    required: false
    default: "."
  packer_version:
    description: "Packer version to use"
    required: false
    default: "1.11.2"
  os_cloud:
    description: "OpenStack cloud name from clouds.yaml (optional)"
    required: false
    default: ""

  # Cloud Configuration Files (base64 encoded)
  cloud_env_json:
    description: "Cloud environment JSON configuration (base64 encoded) - optional, will be generated from vexxhost_* inputs if not provided"
    required: false
    default: ""
  clouds_yaml:
    description: "OpenStack clouds.yaml configuration (base64 encoded, optional)"
    required: false
    default: ""

  # VexxHost/OpenStack Credentials
  vexxhost_auth_url:
    description: "VexxHost/OpenStack auth URL"
    required: false
    default: ""
  vexxhost_project_id:
    description: "VexxHost/OpenStack project/tenant ID"
    required: false
    default: ""
  vexxhost_username:
    description: "VexxHost/OpenStack username"
    required: false
    default: ""
  vexxhost_password:
    description: "VexxHost/OpenStack password (will be base64 decoded if needed)"
    required: false
    default: ""
  vexxhost_region:
    description: "VexxHost/OpenStack region"
    required: false
    default: "ca-ymq-1"
  vexxhost_network_id:
    description: "VexxHost/OpenStack network UUID for Packer builds"
    required: false
    default: ""

  # Bastion Configuration
  bastion_flavor:
    description: "OpenStack flavor for bastion instance"
    required: false
    default: "v3-standard-2"
  bastion_image:
    description: "Base image for bastion host"
    required: false
    default: "Ubuntu 22.04.5 LTS (x86_64) [2025-03-27]"
  bastion_network:
    description: "Network name for bastion host"
    required: false
    default: "odlci"
  bastion_ssh_key:
    description: "SSH key name for bastion (optional, Tailscale SSH used by default)"
    required: false
    default: ""
  bastion_wait_timeout:
    description: "Timeout in seconds to wait for bastion to be ready"
    required: false
    default: "300"

  # Tailscale Configuration (required for build mode only)
  tailscale_auth_key:
    description: "Tailscale auth key for bastion (required for build mode if not using OAuth)"
    required: false
    default: ""
  tailscale_oauth_client_id:
    description: "Tailscale OAuth client ID for runner (alternative to auth key)"
    required: false
    default: ""
  tailscale_oauth_secret:
    description: "Tailscale OAuth secret for runner (alternative to auth key)"
    required: false
    default: ""
  tailscale_version:
    description: "Tailscale version"
    required: false
    default: "latest"

  # Build Options
  debug_mode:
    description: "Enable debug logging"
    required: false
    default: "false"
  upload_logs:
    description: "Upload build logs as artifacts"
    required: false
    default: "true"
  log_retention_days:
    description: "Days to retain log artifacts"
    required: false
    default: "30"

outputs:
  bastion_ip:
    description: "Tailscale IP of the bastion host (build mode only)"
    value: ${{ steps.get-bastion-ip.outputs.bastion_ip }}
  status:
    description: "Status of the operation (success/failure)"
    value: ${{ steps.packer-operation.outputs.status || steps.packer-validate.outputs.status }}
  mode:
    description: "Mode that was executed (validate/build)"
    value: ${{ inputs.mode }}

runs:
  using: "composite"
  steps:
    # ========================================
    # Step 1: Setup Tailscale VPN (Build Mode Only)
    # ========================================
    - name: Setup Tailscale VPN
      if: inputs.mode == 'build'
      uses: tailscale/github-action@9b0941a5b0464aaf849d388c0fb004e3e15d9b92 # v2.0.3
      with:
        oauth_client_id: ${{ inputs.tailscale_oauth_client_id }}
        oauth_secret: ${{ inputs.tailscale_oauth_secret }}
        version: ${{ inputs.tailscale_version }}
        hostname: github-runner-${{ github.run_id }}
        args: up --ssh --verbose=1

    - name: Verify Tailscale connection
      if: inputs.mode == 'build'
      shell: bash
      run: |
        echo "✅ Tailscale status:"
        sudo tailscale status

    # ========================================
    # Step 2: Setup OpenStack CLI (Build Mode Only)
    # ========================================
    - name: Setup Python and OpenStack CLI
      if: inputs.mode == 'build'
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.11"

    - name: Install OpenStack CLI
      if: inputs.mode == 'build'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install python-openstackclient

    - name: Configure OpenStack credentials
      if: inputs.mode == 'build'
      shell: bash
      env:
        OS_AUTH_URL: ${{ inputs.vexxhost_auth_url }}
        OS_PROJECT_ID: ${{ inputs.vexxhost_project_id }}
        OS_USERNAME: ${{ inputs.vexxhost_username }}
        OS_PASSWORD: ${{ inputs.vexxhost_password }}
        OS_REGION_NAME: ${{ inputs.vexxhost_region }}
      run: |
        # Check if password is base64 encoded and decode if needed
        if echo "$OS_PASSWORD" | base64 -d &>/dev/null; then
          PASSWORD=$(echo "$OS_PASSWORD" | base64 -d)
        else
          PASSWORD="$OS_PASSWORD"
        fi

        echo "OS_AUTH_URL=${OS_AUTH_URL}" >> $GITHUB_ENV
        echo "OS_PROJECT_ID=${OS_PROJECT_ID}" >> $GITHUB_ENV
        echo "OS_USERNAME=${OS_USERNAME}" >> $GITHUB_ENV
        echo "OS_PASSWORD=${PASSWORD}" >> $GITHUB_ENV
        echo "OS_REGION_NAME=${OS_REGION_NAME}" >> $GITHUB_ENV
        echo "OS_IDENTITY_API_VERSION=3" >> $GITHUB_ENV
        echo "OS_USER_DOMAIN_NAME=Default" >> $GITHUB_ENV
        echo "OS_PROJECT_DOMAIN_NAME=Default" >> $GITHUB_ENV

    # ========================================
    # Step 3: Create and Launch Bastion Host (Build Mode Only)
    # ========================================
    - name: Create cloud-init script for bastion
      if: inputs.mode == 'build'
      shell: bash
      run: |
        BASTION_NAME="bastion-gh-${{ github.run_id }}"

        cat > cloud-init.yaml <<'EOF'
        #cloud-config
        hostname: ${BASTION_HOSTNAME}
        manage_etc_hosts: true
        package_update: true
        package_upgrade: true
        packages:
          - curl
          - wget
          - jq
          - net-tools
        write_files:
          - path: /usr/local/bin/bastion-init.sh
            content: |
              #!/bin/bash
              set -e
              echo "[$(date)] Installing Tailscale..."
              curl -fsSL https://tailscale.com/install.sh | sh
              tailscale up --authkey="${TAILSCALE_AUTH_KEY}" \
                --hostname="${BASTION_HOSTNAME}" \
                --advertise-tags=tag:bastion \
                --ssh --accept-routes --accept-dns=false
              TAILSCALE_IP=$(tailscale ip -4)
              echo "[$(date)] Tailscale IP: ${TAILSCALE_IP}"
              echo "READY" > /tmp/bastion-ready
            permissions: '0755'
        runcmd:
          - /usr/local/bin/bastion-init.sh
        EOF

        # Substitute variables
        sed -i "s/\${BASTION_HOSTNAME}/$BASTION_NAME/g" cloud-init.yaml
        sed -i "s/\${TAILSCALE_AUTH_KEY}/${{ inputs.tailscale_auth_key }}/g" cloud-init.yaml

        echo "BASTION_NAME=$BASTION_NAME" >> $GITHUB_ENV

    - name: Launch bastion instance
      if: inputs.mode == 'build'
      shell: bash
      run: |
        openstack server create \
          --flavor "${{ inputs.bastion_flavor }}" \
          --image "${{ inputs.bastion_image }}" \
          --nic net-id=${{ inputs.bastion_network }} \
          --user-data cloud-init.yaml \
          --wait \
          "${{ env.BASTION_NAME }}"

    - name: Wait for bastion to join Tailscale
      if: inputs.mode == 'build'
      shell: bash
      run: |
        timeout=${{ inputs.bastion_wait_timeout }}
        elapsed=0

        while [ $elapsed -lt $timeout ]; do
          if sudo tailscale status | grep -q "${{ env.BASTION_NAME }}"; then
            BASTION_IP=$(sudo tailscale status | grep "${{ env.BASTION_NAME }}" | awk '{print $1}')
            echo "✅ Bastion joined Tailscale: $BASTION_IP"
            echo "BASTION_IP=$BASTION_IP" >> $GITHUB_ENV
            exit 0
          fi
          sleep 5
          elapsed=$((elapsed + 5))
        done

        echo "❌ Bastion failed to join Tailscale within ${timeout}s"
        exit 1

    - name: Export bastion IP
      if: inputs.mode == 'build'
      id: get-bastion-ip
      shell: bash
      run: |
        echo "bastion_ip=${{ env.BASTION_IP }}" >> $GITHUB_OUTPUT

    # ========================================
    # Step 4: Setup Packer
    # ========================================
    - name: Setup Packer
      uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
      with:
        version: ${{ inputs.packer_version }}

    - name: Create cloud environment file
      shell: bash
      run: |
        # Check if cloud_env_json is provided
        if [ -n "${{ inputs.cloud_env_json }}" ]; then
          # Use provided cloud_env_json
          if echo "${{ inputs.cloud_env_json }}" | base64 -d &>/dev/null 2>&1; then
            echo "${{ inputs.cloud_env_json }}" | base64 -d > cloud-env.json
          else
            echo '${{ inputs.cloud_env_json }}' > cloud-env.json
          fi
          echo "✅ Using provided cloud_env_json"
        elif [ -n "${{ inputs.vexxhost_auth_url }}" ]; then
          # Generate cloud-env from vexxhost credentials
          # Decode password if base64 encoded
          if echo "${{ inputs.vexxhost_password }}" | base64 -d &>/dev/null 2>&1; then
            CLOUD_PASS=$(echo "${{ inputs.vexxhost_password }}" | base64 -d)
          else
            CLOUD_PASS="${{ inputs.vexxhost_password }}"
          fi

          # Create cloud-env.json
          cat > cloud-env.json <<EOF
        {
          "cloud_auth_url": "${{ inputs.vexxhost_auth_url }}",
          "cloud_tenant": "${{ inputs.vexxhost_project_id }}",
          "cloud_user": "${{ inputs.vexxhost_username }}",
          "cloud_pass": "${CLOUD_PASS}",
          "cloud_network": "${{ inputs.vexxhost_network_id }}"
        }
        EOF
          echo "✅ Generated cloud_env_json from vexxhost credentials"
        else
          echo "⚠️ No cloud environment configuration provided"
        fi

        # Update ssh_proxy_host with bastion IP (build mode only)
        if [ "${{ inputs.mode }}" == "build" ] && [ -f "cloud-env.json" ]; then
          jq --arg ip "${{ env.BASTION_IP }}" '.ssh_proxy_host = $ip' cloud-env.json > cloud-env.tmp.json
          mv cloud-env.tmp.json cloud-env.json
          echo "✅ Updated cloud-env.json with bastion IP: ${{ env.BASTION_IP }}"
        fi

    - name: Create clouds.yaml (optional)
      if: inputs.clouds_yaml != ''
      shell: bash
      run: |
        mkdir -p "$HOME/.config/openstack"
        echo "${{ inputs.clouds_yaml }}" | base64 -d > "$HOME/.config/openstack/clouds.yaml"
        echo "✅ OpenStack clouds.yaml created"

    - name: Setup SSH agent (Build Mode)
      if: inputs.mode == 'build'
      shell: bash
      run: |
        eval "$(ssh-agent -s)"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
        echo "✅ SSH agent started"

    # ========================================
    # Step 5: Run Packer Operation
    # ========================================
    - name: Determine packer directory
      shell: bash
      run: |
        WORK_DIR="${{ inputs.packer_working_dir }}"

        # Check if packer_working_dir points to a subdirectory with packer files
        if [ -d "$WORK_DIR/packer" ]; then
          PACKER_DIR="$WORK_DIR/packer"
        elif [ -d "$WORK_DIR/common-packer" ]; then
          PACKER_DIR="$WORK_DIR/common-packer"
        else
          PACKER_DIR="$WORK_DIR"
        fi

        echo "PACKER_DIR=$PACKER_DIR" >> $GITHUB_ENV
        echo "Using packer directory: $PACKER_DIR"

    - name: Validate all Packer templates (Validate Mode)
      if: inputs.mode == 'validate'
      id: packer-validate
      shell: bash
      env:
        OS_CLOUD: ${{ inputs.os_cloud }}
      run: |
        set -x

        cd "$PACKER_DIR"

        # Find all varfiles and templates
        varfiles=(vars/*.pkrvars.hcl)
        if [ -d "common-packer/vars" ]; then
          varfiles=(common-packer/vars/*.pkrvars.hcl)
        fi

        templates=(templates/*.pkr.hcl)

        # Create logs directory
        mkdir -p "${{ github.workspace }}/logs"
        PACKER_LOGS_DIR="${{ github.workspace }}/logs"

        validation_count=0
        failed_count=0

        # Loop through each varfile
        for varfile in "${varfiles[@]}"; do
          # Skip cloud-env and non-existent files
          if [[ "$varfile" == *"cloud-env"* ]] || \
             [[ "$varfile" == *"vars/*.pkrvars.hcl" ]] || \
             [[ "$varfile" == *"common-packer/vars/*.pkrvars.hcl" ]]; then
            echo "Skipping $varfile"
            continue
          fi

          echo "::group::Validating with $varfile"
          echo "======================================"
          echo "Testing varfile: $varfile"
          echo "======================================"

          # Loop through each template
          for template in "${templates[@]}"; do
            # Skip variables files and non-existent files
            if [[ "$template" == *"variables"* ]] || \
               [[ "$template" == *"templates/*.pkr.hcl" ]]; then
              continue
            fi

            echo "  → Template: $template"

            # Initialize template if needed
            if [[ "${template#*.}" == "pkr.hcl" ]]; then
              echo "    Initializing template..."
              if ! packer init "$template"; then
                echo "    ❌ Failed to initialize $template"
                ((failed_count++))
                continue
              fi
            fi

            # Set up logging
            LOG_FILE="packer-validate-${varfile##*/}-${template##*/}.log"
            export PACKER_LOG="yes"
            export PACKER_LOG_PATH="$PACKER_LOGS_DIR/$LOG_FILE"

            # Build validation command
            VALIDATE_CMD="packer validate"

            # Add cloud-env if it exists
            if [ -f "${{ github.workspace }}/cloud-env.pkrvars.hcl" ]; then
              VALIDATE_CMD="$VALIDATE_CMD -var-file=${{ github.workspace }}/cloud-env.pkrvars.hcl"
            elif [ -f "${{ github.workspace }}/cloud-env.json" ]; then
              VALIDATE_CMD="$VALIDATE_CMD -var-file=${{ github.workspace }}/cloud-env.json"
            fi

            # Add varfile and template
            VALIDATE_CMD="$VALIDATE_CMD -var-file=$varfile $template"

            # Run validation
            echo "    Running: $VALIDATE_CMD"
            if output=$(eval $VALIDATE_CMD 2>&1); then
              echo "    ✅ Validation passed: $output"
              ((validation_count++))
            else
              echo "    ❌ Validation failed: $output"
              ((failed_count++))
            fi
          done
          echo "::endgroup::"
        done

        echo ""
        echo "======================================"
        echo "Validation Summary"
        echo "======================================"
        echo "Total validations passed: $validation_count"
        echo "Total validations failed: $failed_count"
        echo "======================================"

        # Set output
        if [ $failed_count -gt 0 ]; then
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "❌ $failed_count validation(s) failed"
          exit 1
        else
          echo "status=success" >> $GITHUB_OUTPUT
          echo "✅ All $validation_count validations passed"
        fi

    - name: Initialize Packer (Build Mode)
      if: inputs.mode == 'build'
      shell: bash
      run: |
        cd "$PACKER_DIR"
        packer init "${{ inputs.packer_template }}"

    - name: Validate Packer template (Build Mode)
      if: inputs.mode == 'build'
      shell: bash
      env:
        OS_CLOUD: ${{ inputs.os_cloud }}
      run: |
        set -e
        cd "$PACKER_DIR"

        VALIDATE_CMD="packer validate"
        VALIDATE_CMD="$VALIDATE_CMD -var-file=${{ github.workspace }}/cloud-env.json"
        VALIDATE_CMD="$VALIDATE_CMD -var-file=${{ inputs.packer_vars_file }}"
        VALIDATE_CMD="$VALIDATE_CMD -var=bastion_host=${{ env.BASTION_IP }}"
        VALIDATE_CMD="$VALIDATE_CMD ${{ inputs.packer_template }}"

        echo "Running: $VALIDATE_CMD"
        if $VALIDATE_CMD; then
          echo "✅ Packer validation successful"
        else
          echo "❌ Packer validation failed"
          exit 1
        fi

    - name: Build with Packer (Build Mode Only)
      if: inputs.mode == 'build'
      id: packer-operation
      shell: bash
      env:
        PACKER_LOG: ${{ inputs.debug_mode == 'true' && '1' || '0' }}
        OS_CLOUD: ${{ inputs.os_cloud }}
      run: |
        set +e
        cd "$PACKER_DIR"

        packer build \
          -var-file="${{ github.workspace }}/cloud-env.json" \
          -var-file="${{ inputs.packer_vars_file }}" \
          -var="bastion_host=${{ env.BASTION_IP }}" \
          -var="bastion_user=root" \
          "${{ inputs.packer_template }}"

        BUILD_EXIT_CODE=$?

        if [ $BUILD_EXIT_CODE -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "✅ Packer build completed successfully"
          exit 0
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "❌ Packer build failed with exit code $BUILD_EXIT_CODE"
          exit $BUILD_EXIT_CODE
        fi

    # ========================================
    # Step 6: Cleanup
    # ========================================
    - name: Cleanup bastion instance
      if: always() && inputs.mode == 'build'
      shell: bash
      run: |
        openstack server delete --wait "${{ env.BASTION_NAME }}" || true
        echo "✅ Bastion instance cleaned up"
