---
# SPDX-License-Identifier: Apache-2.0
# Test workflow for Packer Action

name: Test Packer Action

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Action mode (validate or build)"
        required: false
        type: choice
        options:
          - validate
          - build
        default: "validate"
      packer_vars:
        description: "Packer vars file (e.g., ubuntu-22.04)"
        required: false
        type: string
        default: "ubuntu-22.04"
      debug_mode:
        description: "Enable debug logging"
        required: false
        type: boolean
        default: false
  push:
    branches: [main]
    paths:
      - "examples/**"
      - "action.yaml"
      - ".github/workflows/test-action.yaml"
  pull_request:
    branches: [main]
    paths:
      - "examples/**"
      - "action.yaml"
      - ".github/workflows/test-action.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-validate:
    name: Test Action - Validate Mode
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch' && inputs.mode == 'validate')
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
        with:
          submodules: true

      - name: Run Packer Action - Validate
        uses: ./
        with:
          mode: validate
          packer-dir: examples
          template-path: templates/builder.pkr.hcl
          var-file: vars/ubuntu-22.04.pkrvars.hcl
          cloud-name: vexxhost
          debug: ${{ inputs.debug_mode || false }}
        env:
          VEXXHOST_AUTH_URL: ${{ secrets.VEXXHOST_AUTH_URL }}
          VEXXHOST_PROJECT_ID: ${{ secrets.VEXXHOST_PROJECT_ID }}
          VEXXHOST_USERNAME: ${{ secrets.VEXXHOST_USERNAME }}
          VEXXHOST_PASSWORD_B64: ${{ secrets.VEXXHOST_PASSWORD_B64 }}
          VEXXHOST_PASSWORD: ${{ secrets.VEXXHOST_PASSWORD }}
          VEXXHOST_NETWORK_ID: ${{ secrets.VEXXHOST_NETWORK_ID }}
          VEXXHOST_REGION: ${{ secrets.VEXXHOST_REGION }}

  test-build:
    name: Test Action - Build Mode
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' && inputs.mode == 'build'
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
        with:
          submodules: true

      - name: Run Packer Action - Build
        uses: ./
        with:
          mode: build
          packer-dir: examples
          template-path: templates/builder.pkr.hcl
          var-file: vars/ubuntu-22.04.pkrvars.hcl
          cloud-name: vexxhost
          bastion-flavor: v3-standard-2
          bastion-image: "Ubuntu 22.04.5 LTS (x86_64) [2025-03-27]"
          bastion-network: odlci
          debug: ${{ inputs.debug_mode || false }}
        env:
          TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          TAILSCALE_OAUTH_SECRET: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          VEXXHOST_AUTH_URL: ${{ secrets.VEXXHOST_AUTH_URL }}
          VEXXHOST_PROJECT_ID: ${{ secrets.VEXXHOST_PROJECT_ID }}
          VEXXHOST_USERNAME: ${{ secrets.VEXXHOST_USERNAME }}
          VEXXHOST_PASSWORD_B64: ${{ secrets.VEXXHOST_PASSWORD_B64 }}
          VEXXHOST_PASSWORD: ${{ secrets.VEXXHOST_PASSWORD }}
          VEXXHOST_NETWORK_ID: ${{ secrets.VEXXHOST_NETWORK_ID }}
          VEXXHOST_REGION: ${{ secrets.VEXXHOST_REGION }}

      - name: Display build output
        if: always()
        run: |
          echo "## Build Results" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "- **Image Name:** ${{ steps.build.outputs.image-name || 'N/A' }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- **Status:** ${{ job.status }}" >> "$GITHUB_STEP_SUMMARY"

  summary:
    name: Test Summary
    if: always()
    needs: [test-validate, test-build]
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary
        run: |
          {
            echo "## Packer Action Test Summary"
            echo ""
            echo "- **Workflow:** ${{ github.workflow }}"
            echo "- **Run ID:** ${{ github.run_id }}"
            echo "- **Trigger:** ${{ github.event_name }}"
            echo "- **Mode:** ${{ inputs.mode || 'auto (validate)' }}"
            echo ""
            echo "### Job Results"
            echo "- **Validate:** ${{ needs.test-validate.result }}"
            echo "- **Build:** ${{ needs.test-build.result }}"
          } >> "$GITHUB_STEP_SUMMARY"
